# Generated by Django 3.0.7 on 2022-06-07 19:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictCapitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('adm2_en', models.CharField(blank=True, max_length=50, null=True)),
                ('adm2_pcode', models.CharField(blank=True, max_length=50, null=True)),
                ('adm2_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('adm2alt1en', models.CharField(blank=True, max_length=50, null=True)),
                ('adm2alt2en', models.CharField(blank=True, max_length=50, null=True)),
                ('adm1_en', models.CharField(blank=True, max_length=50, null=True)),
                ('adm1_pcode', models.CharField(blank=True, max_length=50, null=True)),
                ('adm0_en', models.CharField(blank=True, max_length=50, null=True)),
                ('adm0_pcode', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('validon', models.DateField(blank=True, null=True)),
                ('validto', models.DateField(blank=True, null=True)),
                ('point_x', models.FloatField(blank=True, null=True)),
                ('point_y', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'district_capitals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_providers', models.IntegerField(default=0)),
                ('number_of_districts', models.IntegerField(default=0)),
                ('budget', models.FloatField(default=0.0, null=True)),
                ('priority', models.CharField(default='No', max_length=15)),
            ],
            options={
                'db_table': 'regions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('district_n', models.CharField(blank=True, max_length=29, null=True)),
                ('number_of_providers', models.IntegerField(default=0)),
                ('budget', models.FloatField(default=0.0, null=True)),
                ('priority', models.CharField(default='No', max_length=15)),
                ('referred_cases', models.IntegerField(default=0)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serices.Regions')),
            ],
            options={
                'db_table': 'districts',
                'managed': True,
            },
        ),
    ]
